// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqjsqytpnvadvcbnizxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxanNxeXRwbnZhZHZjYm5penhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzU0MzMsImV4cCI6MjA3MDExMTQzM30.QJWiPcmoJolNEBPNDR0OrjdWHqZ4WBhoxOFG4ZVXlPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});